# ----------------------------------------
# Created on: Sat Nov  2 16:46:12 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "Y:/SoftWare/Modelsim/pango_sim_test_lib/usim"
vmap  adc "Y:/SoftWare/Modelsim/pango_sim_test_lib/adc"
vmap  ddrc "Y:/SoftWare/Modelsim/pango_sim_test_lib/ddrc"
vmap  ddrphy "Y:/SoftWare/Modelsim/pango_sim_test_lib/ddrphy"
vmap  hsst_e2 "Y:/SoftWare/Modelsim/pango_sim_test_lib/hsst_e2"
vmap  iolhr_dft "Y:/SoftWare/Modelsim/pango_sim_test_lib/iolhr_dft"
vmap  ipal_e1 "Y:/SoftWare/Modelsim/pango_sim_test_lib/ipal_e1"
vmap  pciegen2 "Y:/SoftWare/Modelsim/pango_sim_test_lib/pciegen2"
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/eth_udp_test.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/ethernet_test.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/icmp.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/ip_layer.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/ip_rx.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/ip_tx.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/ip_tx_mode.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/udp_ip_mac_top.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/udp_layer.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/udp_tx.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/rgmii_interface.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/arp_mac_top.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/arp_cache.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/arp_rx.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/arp_tx.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/mac_layer.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/mac_rx.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/mac_tx.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/mac_tx_mode.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/crc32_gen.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/check_sum.vh" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/udp_rx.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/top.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/adda.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/adc_capture.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/test_ddr.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/ddr_ctrl.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/icmp_rx_ram_8_256/rtl/ipml_sdpram_v1_6_icmp_rx_ram_8_256.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/icmp_rx_ram_8_256/icmp_rx_ram_8_256.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/udp_shift_register/rtl/ipm_distributed_sdpram_v1_2_udp_shift_register.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/udp_shift_register/rtl/ipm_distributed_shiftregister_v1_3_udp_shift_register.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/udp_shift_register/udp_shift_register.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ref_clock/ref_clock.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ad_clock_125m/ad_clock_125m.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/fifo_buffer/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/fifo_buffer/rtl/ipml_sdpram_v1_6_fifo_buffer.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/fifo_buffer/rtl/ipml_fifo_v1_6_fifo_buffer.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/fifo_buffer/fifo_buffer.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/ddr_test.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/ddr_test_ddrphy_top.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ipsxb_rst_sync_v1_1.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_calib_mux_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_calib_top_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_control_path_adj_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_data_slice_v1_4.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_data_slice_dqs_gate_cal_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_data_slice_wrlvl_v1_4.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dfi_v1_4.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dll_update_ctrl_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dqsi_rdel_cal_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dqs_gate_coarse_cal_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_dqs_rddata_align_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_drift_ctrl_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_gate_update_ctrl_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_gatecal_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_info_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_init_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_main_ctrl_v1_3.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_rdcal_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_reset_ctrl_v1_4.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_rst_debounce_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_slice_rddata_align_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_training_ctrl_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_upcal_v1_4.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_wdata_path_adj_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_wrlvl_v1_0.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/ddrphy/ipsxb_ddrphy_slice_top_v1_4.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/pll/ipsxb_ddrphy_pll_v1_0.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_apb_cross_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_calib_delay_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_cfg_apb_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_bm_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_rowaddr_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_sm_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcd_top_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_back_ctrl_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_buf_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_out_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dcp_top_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_dfi_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_lp_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_mrs_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_prefetch_fifo_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_rdatapath_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_reg_fifo2_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_ui_axi_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_wdatapath_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_align_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_wdp_dcp_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/ipsxb_mcdq_wrapper_v1_2a.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_com_timing_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_timing_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_tfaw_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act2wr_pass_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_act_pass_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_pre_pass_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_rd_pass_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_ref_pass_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_timing_wr_pass_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/syn_mod/ipsxb_mcdq_trc_timing_v1_2.vp" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/distributed_fifo/ipsxb_distributed_fifo_v1_0.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_ctr_v1_0.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_fifo_v1_0_distributed_fifo_v1_0.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/ipcore/ddr_test/rtl/mcdq_ctrl/distributed_fifo/rtl/ipsxb_distributed_sdpram_v1_0_distributed_fifo_v1_0.v" -work work
vlog   "E:/DELL/Desktop/FPGA/FPGA_DevelopKnit/MES50HP_v3/2_Demo/11_ethernet_test/source/tb_ddr3_simu.v" -work work

# ----------------------------------------
