# ----------------------------------------
# Created on: Sat Nov  2 16:46:12 2024
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 tb_ddr3_simu usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
